---
format: gfm
---

Reproducible slides for my presentation at Data Driven 2025.

See [www.robinlovelace.net/talk/data-driven-2025/](https://www.robinlovelace.net/talk/data-driven-2025/) for the slides.

See below for details on how this was set-up.

<details>

```{bash}
#| eval: false
gh repo clone robinlovelace/gisruk2025
cp -rv ../gisruk2025/images .
cp -rv ../gisruk2025/slides.qmd .
cp -rv ../gisruk2025/_quarto.yml .
cp -rv ../gisruk2025/.devcontainer.json .
cp -rv ../gisruk2025/references.bib .
# Or if you have it locally:
cp -rv ../gisruk2025/. .
git add slides.qmd
git add images
git status
```

```{bash}
#| eval: false
quarto add grantmcdermott/quarto-revealjs-clean
```

# reproducible-slides-repo-template

Flexible repo template for reproducible slides with Quarto and continuous deployment via GitHub actions

See https://robinlovelace.github.io/reproducible-slides-repo-template/slides for the content, the most important parts of which are:

- You can use this repo as a template for your own reproducible slides
- Quarto is a powerful tool for creating reproducible documents
- Set-up GitHub pages with:

```sh
quarto publish gh-pages
```

- Use [GitHub actions](.github/workflows/) to automatically deploy your slides to GitHub pages

## Reproducible slide projects build with this

- Deploying cross-language in high impact projects, auto-updated and deployed with every commit, with R and Python code running and generating results shown in the slides: https://github.com/Robinlovelace/cross_language_projects